"use client";

import type { DashboardConfig } from "@/lib/parseChartBlocks";
import { FrappeChart } from "./FrappeChart";

interface DashboardProps {
  config: DashboardConfig;
}

export function Dashboard({ config }: DashboardProps) {
  const columns = config.columns || 2;

  return (
    <div className="animate-chart-reveal">
      <div className="border border-black/10 rounded-[2px] bg-[#fafaf9] p-6 overflow-hidden">
        {/* Dashboard Header */}
        <div className="mb-6 pb-4 border-b border-black/10">
          <div className="flex items-center justify-between">
            <div>
              <span className="text-[10px] uppercase tracking-widest text-black/40 font-medium block mb-1">
                Dashboard
              </span>
              <h3 className="font-serif text-lg font-light text-[#1c1917]">
                {config.title}
              </h3>
              {config.description && (
                <p className="text-xs text-black/50 font-light mt-1">
                  {config.description}
                </p>
              )}
            </div>
            <div className="w-8 h-8 rounded-full bg-[#1c1917] flex items-center justify-center flex-shrink-0">
              <svg
                width="14"
                height="14"
                viewBox="0 0 24 24"
                fill="none"
                stroke="white"
                strokeWidth="1.5"
                strokeLinecap="round"
                strokeLinejoin="round"
              >
                <rect x="3" y="3" width="7" height="7" />
                <rect x="14" y="3" width="7" height="7" />
                <rect x="3" y="14" width="7" height="7" />
                <rect x="14" y="14" width="7" height="7" />
              </svg>
            </div>
          </div>
        </div>

        {/* KPI Cards */}
        {config.kpis && config.kpis.length > 0 && (
          <div
            className="grid gap-3 mb-6"
            style={{
              gridTemplateColumns: `repeat(${Math.min(config.kpis.length, 4)}, 1fr)`,
            }}
          >
            {config.kpis.map((kpi, index) => (
              <div
                key={index}
                className="bg-white border border-black/10 rounded-[2px] p-4"
              >
                <span className="text-[9px] uppercase tracking-widest text-black/40 font-medium block mb-2">
                  {kpi.label}
                </span>
                <div className="flex items-end gap-2">
                  <span className="font-serif text-xl font-light text-[#1c1917]">
                    {kpi.value}
                  </span>
                  {kpi.change && (
                    <span
                      className={`text-[10px] font-medium pb-0.5 ${
                        kpi.trend === "up"
                          ? "text-[#4a7c6f]"
                          : kpi.trend === "down"
                            ? "text-[#c0392b]"
                            : "text-black/40"
                      }`}
                    >
                      {kpi.trend === "up" && "\u2191"}
                      {kpi.trend === "down" && "\u2193"}
                      {kpi.change}
                    </span>
                  )}
                </div>
              </div>
            ))}
          </div>
        )}

        {/* Charts Grid */}
        <div
          className="grid gap-4"
          style={{
            gridTemplateColumns: `repeat(${columns}, 1fr)`,
          }}
        >
          {config.charts.map((chart, index) => (
            <div
              key={index}
              className={
                chart.type === "heatmap" ||
                (chart.type === "line" && config.charts.length > 2)
                  ? `col-span-${columns}`
                  : ""
              }
              style={
                chart.type === "heatmap"
                  ? { gridColumn: `1 / -1` }
                  : undefined
              }
            >
              <FrappeChart config={chart} />
            </div>
          ))}
        </div>

        {/* Dashboard Footer */}
        <div className="mt-4 pt-3 border-t border-black/5 flex items-center justify-between">
          <span className="text-[9px] uppercase tracking-widest text-black/25 font-medium">
            {config.charts.length} visualization
            {config.charts.length !== 1 ? "s" : ""}
          </span>
          <span className="text-[9px] uppercase tracking-widest text-black/25 font-medium">
            Generated by Frippr
          </span>
        </div>
      </div>
    </div>
  );
}
